config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: "home#index"
  post '/search', to: "home#search_postit"
  post '/create', to: "home#create_post"
  delete '/destroy/:id', to: "home#destroy_postit"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interface_api.rb
class InterfaceApi < ApplicationRecord
	require 'rest-client'

	def self.all_postits
		resp = RestClient.get "localhost:3000/api/v1/postit/all_postits"
		resp = JSON.parse(resp)
	end

	def self.search_postit(id)
		resp = RestClient.get "localhost:3000/api/v1/postit/search/#{id}"
		resp = JSON.parse(resp)
	end

	def self.create_post(title, description)
		url = "localhost:3000/api/v1/postit/create"
		data = {title: title, description: description}
		resp = RestClient.post(url, data)
		resp = JSON.parse(resp)
	end

	def self.destroy(id)
		resp = RestClient.delete "localhost:3000/api/v1/postit/destroy/#{id}"			
		resp = JSON.parse(resp)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'application'

	def index
		@posts = InterfaceApi::all_postits
	end

	def search_postit
		@post = InterfaceApi::search_postit(params[:id])
		respond_to do |format|
			format.html{redirect_to '/'}
			format.js
		end
	end

	def create_post
		@create = InterfaceApi::create_post(params[:title], params[:description])
		@posts = InterfaceApi::all_postits
			if @create
				respond_to do |format|
					format.html{redirect_to '/'}
					format.js
				end
			end
	end

	def destroy_postit
		post = InterfaceApi::destroy(params[:id])
		@posts = InterfaceApi::all_postits

		respond_to do |format|
			format.html{redirect_to '/'}
			format.js
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_input_search.html.erb
<%= form_with(url: '/search/', method: :post, local: false)  do |format|%>
	<div class="form-group">
		<input class="form-control" type="text" name="id" placeholder="informe um id">
	</div>
	<button class="btn btn-primary mt-1">Pesquisar</button>
<% end %>
<%= link_to 'Todos os Post-it', '/', class: "btn btn-slate mt-2" %>

app/views/home/_list_posts.html.erb
<div id="id_container_post" class="card-container">
	<h3 class="title-color pl-5 title-p" >Suas notas</h3>
	<div id="teste" class="d-flex flex-wrap justify-content-between">
	
	<!-- Cards-->	
		<% @posts.each do |post| %>
			<div class="my-card col-3 shadow offset-md-1">
				<h6 class="my-card-title"><%= post['title'] %></h6>
				<p class="my-card-text">id - <%= post['id'] %></p>
				<p class="my-card-text"><%= post['description'] %></p>
				<%= link_to '', "/destroy/#{post['id']}", method: :delete, confirm: 'tem certeza que deseja deletar esse post it?' ,class: "my-icon-card fas fa-times-circle my-card-close", :remote => true %>
			</div>
		<% end %>
	</div>
	<!-- Fim Cards -->
</div>

app/views/home/_message.html.erb
<div id="modal" class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button id='close-modal' type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body d-flex justify-content-center">
        <h4><%= message['message'] %></h4>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
  $('#close-modal').on('click', function(){
    $('#modal').hide();
  });
</script>

app/views/home/_new_post.html.erb
<div >
	<%= form_with(url: create_path, method: :post, local: false) do |format| %>
		<h3 class="mb-5 title-color">Bloco de notas</h3>
		<div class="form-group mb-3">
			<input class="form-control" type="text" name="title" placeholder="Assunto">
		</div>
		<div class="form-group">
			<textarea class="form-control" rows=5 placeholder="texto" name="description"></textarea>
		</div>
		<input class="btn btn-primary mt-3" type="submit" name="submit" value="Criar Nota">

	<% end %>
</div>

app/views/home/_post.html.erb
<div id="id_container_post" class="card-container">
		<h3 class="title-color pl-5 title-p" >Suas notas</h3>
		<div class="my-card col-3 shadow offset-md-1">
			<h6 class="my-card-title"><%= post['title'] %></h6>
			<p class="my-card-text">id - <%= post['id'] %></p>
			<p class="my-card-text"><%= post['description'] %></p>

			<%= link_to '', "/destroy/#{post['id']}", method: :delete, confirm: 'tem certeza que deseja deletar esse post it?' ,class: "my-icon-card fas fa-times-circle my-card-close", :remote => true %>
		</div>
</div>

app/views/home/create_post.js.erb
$("<%=  j (render 'message', message: @create)%>").appendTo("#message");
$("#id_container_post").remove();
$("<%=  j (render 'list_posts', posts: @posts)%>").appendTo("#posts");
$('#modal').show();

app/views/home/destroy_postit.js.erb
$("#id_container_post").remove();
$("<%=  j (render 'list_posts', posts: @posts)%>").appendTo("#posts");

app/views/home/index.html.erb
<div id="message" class="">
</div>

<div class="container mt-3 d-flex flex-wrap">
  <div class="row col-12">
    <div class="col-12 mb-5">
      <%= render 'input_search' %>
    </div>
    <div class="col-4 border-right-orange">
      <%= render 'new_post' %>
    
    </div>
    <div id="posts" class="col-8">
      <%= render 'list_posts'%>
    </div>
  </div>
</div>

app/views/home/search_postit.js.erb
$("#id_container_post").remove();
$("<%=  j (render 'post', post: @post)%>").appendTo("#posts");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostItRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- CSS bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- JS Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <!-- CDN jquery -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

  <!-- CDN Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
  
  <body>
    <%= yield %>
  </body>
</html>